-- @operation: export
-- @entity: batch
-- @name: english audio anime regex fix
-- @exportedAt: 2026-09-05T17:01:43.635Z
-- @opIds: 2337

-- --- BEGIN op 2337 ( update regular_expression "English Audio Anime" )
update "regular_expressions" set "pattern" = '(?i)(?:\b(?:dual|multi)[\s._-]?(?:audio|lang(?:uage)?s?)\b|\b2[\s._-]?audio\b|[\[(]dual(?:[\s._-]?audio)?[\])]|\b(?:eng(?:lish)?[\s._-]?(?:dub(?:bed|bing)?|audio|only)|dubbed)\b|\b(?:japanese|jpn|jap|ja|jp|chinese|chs|cht|chi|zho|zh|korean|kor|ko)[\s._+\-&/\[\]()]{1,3}(?:english|eng|en)\b|\b(?:english|eng|en)[\s._+\-&/\[\]()]{1,3}(?:japanese|jpn|jap|ja|jp|chinese|chs|cht|chi|zho|zh|korean|kor|ko)\b|^(?=[^\n]*\b(?:\d{3,4}[pi]|4k|u(?:ltra)?hd)\b)(?![^\n]*\b(?:german|deutsch|french|truefrench|vff|vfq|vfi|vostfr|italian|ita|spanish|castellano|latino|russian|rus|polish|pl|hindi|tamil|telugu|portuguese|dublado)\b)[^\n]*\b(?:dual|multi[\s._-]?dub(?:bed|s)?)\b|(?<=[\[\(-])(?:Kametsu|Golumpa|LostYears|Exiled-Destiny|Koten_Gars|DragsterPS|Small-Maze|Bunny-Apocalypse|Naiyas|Hark0n|KAWAI|TTGA|Aone|FraMeSToR|CiNEPHiLES|BLURANiUM|EPSiLON|TRiToN|WiLDCAT|Neo-HEVC|ANThELIa|xSales|iAHD|DON|PmP|NAN0|NANO|FLUX|decibeL|BMDragon|TayTO|playBD|ZR|ZQ|3L|CTR|MK)(?=[\]\)\s._\-]|\b|$))' where "name" = 'English Audio Anime' and "pattern" = '(?i)(?:\b(?:dual|multi)[\s._-]?(?:audio|lang(?:uage)?s?)\b|\b2[\s._-]?audio\b|\[dual(?:-audio)?\]|\b(?:eng(?:lish)?[\s._-]?(?:dub(?:bed|bing)?|audio|only)|dubbed)\b|\b(?:japanese|jpn|jap|ja|jp|chinese|chs|cht|chi|zho|zh|korean|kor|ko)[\s._+\-&/\[\]()]{1,3}(?:english|eng|en)\b|\b(?:english|eng|en)[\s._+\-&/\[\]()]{1,3}(?:japanese|jpn|jap|ja|jp|chinese|chs|cht|chi|zho|zh|korean|kor|ko)\b|(?<=[\[\(-])(?:Kametsu|Golumpa|LostYears|Exiled-Destiny|Koten_Gars|DragsterPS|Small-Maze|Bunny-Apocalypse|Naiyas|Hark0n|KAWAI|TTGA|Aone|FraMeSToR|CiNEPHiLES|BLURANiUM|EPSiLON|TRiToN|WiLDCAT|Neo-HEVC|ANThELIa|xSales|iAHD|DON|PmP|NAN0|NANO|FLUX|decibeL|BMDragon|TayTO|playBD|ZR|ZQ|3L|CTR|MK)(?=[\]\)\s._\-]|\b|$))';
-- --- END op 2337
