-- @operation: export
-- @entity: batch
-- @name: vostfr veto
-- @exportedAt: 2026-09-05T17:42:31.185Z
-- @opIds: 2340

-- --- BEGIN op 2340 ( update regular_expression "English Audio Anime" )
update "regular_expressions" set "pattern" = '(?i)^(?![^\n]*\b(?:VOST[^\n]*?FR(?:E|A)?\b|SUBFR(?:A|ENCH)?\b))(?:[^\n]*\b(?:eng(?:lish)?[\s._-]?(?:dub(?:bed|bing|s)?|audio|only))\b|[^\n]*\bdubbed[\s._-]?(?:in[\s._-]?)?english\b|[^\n]*\b(?:japanese|jpn|jap|ja|jp|chinese|chs|cht|chi|zho|zh|korean|kor|ko)[\s._+\-&/\[\]()]{1,3}(?:english|eng|en)\b|[^\n]*\b(?:english|eng|en)[\s._+\-&/\[\]()]{1,3}(?:japanese|jpn|jap|ja|jp|chinese|chs|cht|chi|zho|zh|korean|kor|ko)\b|(?=[^\n]*\benglish\b)(?=[^\n]*\bdub(?:s|bed|bing)?\b)|(?![^\n]*\b(?:german|germany|deutsch|ger|french|truefrench|vff|vfq|vfi|italian|italiano|spanish|espanol|castellano|latino|russian|polish|hindi|tamil|telugu|portuguese|dublado|turkish|arabic)\b)(?:[^\n]*\b(?:dual|multi)[\s._-]?(?:audio|lang(?:uage)?s?)\b|[^\n]*\b2[\s._-]?audio\b|[^\n]*[\[(]dual(?:[\s._-]?audio)?[\])]|[^\n]*\bdubbed\b|(?=[^\n]*\b(?:\d{3,4}[pi]|4k|u(?:ltra)?hd)\b)[^\n]*\b(?:dual|multi[\s._-]?dub(?:bed|s)?)\b)|[^\n]*(?<=[\[\(-])(?:Kametsu|Golumpa|LostYears|Exiled-Destiny|Koten_Gars|DragsterPS|Small-Maze|Bunny-Apocalypse|Naiyas|Hark0n|KAWAI|TTGA|Aone|FraMeSToR|CiNEPHiLES|BLURANiUM|EPSiLON|TRiToN|WiLDCAT|Neo-HEVC|ANThELIa|xSales|iAHD|DON|PmP|NAN0|NANO|FLUX|decibeL|BMDragon|TayTO|playBD|ZR|ZQ|3L|CTR|MK)(?=[\]\)\s._\-]|\b|$))' where "name" = 'English Audio Anime' and "pattern" = '(?i)(?:\b(?:eng(?:lish)?[\s._-]?(?:dub(?:bed|bing|s)?|audio|only))\b|\bdubbed[\s._-]?(?:in[\s._-]?)?english\b|\b(?:japanese|jpn|jap|ja|jp|chinese|chs|cht|chi|zho|zh|korean|kor|ko)[\s._+\-&/\[\]()]{1,3}(?:english|eng|en)\b|\b(?:english|eng|en)[\s._+\-&/\[\]()]{1,3}(?:japanese|jpn|jap|ja|jp|chinese|chs|cht|chi|zho|zh|korean|kor|ko)\b|^(?=[^\n]*\benglish\b)(?=[^\n]*\bdub(?:s|bed|bing)?\b)|^(?![^\n]*\b(?:german|germany|deutsch|ger|french|truefrench|vff|vfq|vfi|italian|italiano|spanish|espanol|castellano|latino|russian|polish|hindi|tamil|telugu|portuguese|dublado|turkish|arabic)\b)(?:[^\n]*\b(?:dual|multi)[\s._-]?(?:audio|lang(?:uage)?s?)\b|[^\n]*\b2[\s._-]?audio\b|[^\n]*[\[(]dual(?:[\s._-]?audio)?[\])]|[^\n]*\bdubbed\b|(?=[^\n]*\b(?:\d{3,4}[pi]|4k|u(?:ltra)?hd)\b)[^\n]*\b(?:dual|multi[\s._-]?dub(?:bed|s)?)\b)|(?<=[\[\(-])(?:Kametsu|Golumpa|LostYears|Exiled-Destiny|Koten_Gars|DragsterPS|Small-Maze|Bunny-Apocalypse|Naiyas|Hark0n|KAWAI|TTGA|Aone|FraMeSToR|CiNEPHiLES|BLURANiUM|EPSiLON|TRiToN|WiLDCAT|Neo-HEVC|ANThELIa|xSales|iAHD|DON|PmP|NAN0|NANO|FLUX|decibeL|BMDragon|TayTO|playBD|ZR|ZQ|3L|CTR|MK)(?=[\]\)\s._\-]|\b|$))';
-- --- END op 2340
